name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Web Project
        run: |
          npm run build
          mkdir -p out && touch out/index.html 

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Create Keystore
        run: |
          keytool -genkey -v -keystore android/app/keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-key-alias -dname "CN=, OU=, O=, L=, S=, C=" -storepass my-secret-password -keypass my-secret-password

      - name: Build APK (Release)
        run: |
          npx cap sync android
          chmod +x android/gradlew
          cd android && ./gradlew assembleRelease

      - name: Sign APK
        run: |
            jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore android/app/keystore.jks -storepass my-secret-password android/app/build/outputs/apk/release/app-release-unsigned.apk my-key-alias

      - name: Zipalign APK
        run: |
            ~/Android/sdk/build-tools/34.0.0/zipalign -v 4 android/app/build/outputs/apk/release/app-release-unsigned.apk android/app/build/outputs/apk/release/sanad-app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sanad-app-release
          path: android/app/build/outputs/apk/release/sanad-app-release.apk
